sonar.projectName=helmseed
sonar.projectKey=nullcroft_helmseed_e3b07348-a14b-4c78-9a88-9cfa65eae8c2
sonar.sources=.
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=**/vendor/**,**/dist/**,**/build/**,**/.git/**